// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/limiter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The Input
type AllowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // Who is making the request?
	ActionKey     string                 `protobuf:"bytes,2,opt,name=action_key,json=actionKey,proto3" json:"action_key,omitempty"`     // What are they doing? (e.g., "login", "upload")
	Capacity      int64                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`                       // Max burst size
	RefillRate    int64                  `protobuf:"varint,4,opt,name=refill_rate,json=refillRate,proto3" json:"refill_rate,omitempty"` // Tokens per second
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowRequest) Reset() {
	*x = AllowRequest{}
	mi := &file_proto_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowRequest) ProtoMessage() {}

func (x *AllowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowRequest.ProtoReflect.Descriptor instead.
func (*AllowRequest) Descriptor() ([]byte, []int) {
	return file_proto_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *AllowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AllowRequest) GetActionKey() string {
	if x != nil {
		return x.ActionKey
	}
	return ""
}

func (x *AllowRequest) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *AllowRequest) GetRefillRate() int64 {
	if x != nil {
		return x.RefillRate
	}
	return 0
}

// The Output
type AllowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"` // True if request can proceed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowResponse) Reset() {
	*x = AllowResponse{}
	mi := &file_proto_limiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowResponse) ProtoMessage() {}

func (x *AllowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowResponse.ProtoReflect.Descriptor instead.
func (*AllowResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *AllowResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

var File_proto_limiter_proto protoreflect.FileDescriptor

const file_proto_limiter_proto_rawDesc = "" +
	"\n" +
	"\x13proto/limiter.proto\x12\alimiter\"\x83\x01\n" +
	"\fAllowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"action_key\x18\x02 \x01(\tR\tactionKey\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x03R\bcapacity\x12\x1f\n" +
	"\vrefill_rate\x18\x04 \x01(\x03R\n" +
	"refillRate\")\n" +
	"\rAllowResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed2E\n" +
	"\vRateLimiter\x126\n" +
	"\x05Allow\x12\x15.limiter.AllowRequest\x1a\x16.limiter.AllowResponseB(Z&github.com/yourname/rate-limiter/protob\x06proto3"

var (
	file_proto_limiter_proto_rawDescOnce sync.Once
	file_proto_limiter_proto_rawDescData []byte
)

func file_proto_limiter_proto_rawDescGZIP() []byte {
	file_proto_limiter_proto_rawDescOnce.Do(func() {
		file_proto_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_limiter_proto_rawDesc), len(file_proto_limiter_proto_rawDesc)))
	})
	return file_proto_limiter_proto_rawDescData
}

var file_proto_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_limiter_proto_goTypes = []any{
	(*AllowRequest)(nil),  // 0: limiter.AllowRequest
	(*AllowResponse)(nil), // 1: limiter.AllowResponse
}
var file_proto_limiter_proto_depIdxs = []int32{
	0, // 0: limiter.RateLimiter.Allow:input_type -> limiter.AllowRequest
	1, // 1: limiter.RateLimiter.Allow:output_type -> limiter.AllowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_limiter_proto_init() }
func file_proto_limiter_proto_init() {
	if File_proto_limiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_limiter_proto_rawDesc), len(file_proto_limiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_limiter_proto_goTypes,
		DependencyIndexes: file_proto_limiter_proto_depIdxs,
		MessageInfos:      file_proto_limiter_proto_msgTypes,
	}.Build()
	File_proto_limiter_proto = out.File
	file_proto_limiter_proto_goTypes = nil
	file_proto_limiter_proto_depIdxs = nil
}
